orders/urls.py
from django.urls import path
from .views import checkout, orders
from accounts.views import add_user_address

app_name = 'orders'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('list/', orders, name='user-orders'),
    path('add_user_address/', add_user_address, name='add_user_address'),
]

orders/models.py
# from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save
from decimal import Decimal

from accounts.models import UserAddress
from carts.models import Cart
from ecommerce.utils import unique_order_id_generator

# USER = get_user_model()

# dropdown list for merchents
ORDER_STATUS_CHOICES = (
    ('created','Created'),
    ('paid','Paid'),
    ('shipped','Shipped'),
    ('refunded','Refunded'),
)

try:
    tax_rate =settings.DEFAULT_TAX_RATE
except:
    tax_rate = 0.18

class Order(models.Model):
    user            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, blank=True, null=True)
    order_id        = models.CharField(max_length=120, blank=True, unique=True)
    # billing_profile = ?
    shipping_address= models.ForeignKey(UserAddress, on_delete=models.DO_NOTHING, related_name='shipping_address', null=True)
    billing_address = models.ForeignKey(UserAddress, on_delete=models.DO_NOTHING, related_name='billing_address', null=True)
    cart            = models.ForeignKey(Cart,on_delete=models.DO_NOTHING)
    status          = models.CharField(max_length=120, default= 'created', choices=ORDER_STATUS_CHOICES)
    shipping_total  = models.DecimalField(default=40.00, max_digits=20, decimal_places=2)
    total           = models.DecimalField(default=00.00, max_digits=20, decimal_places=2)

    def __str__(self):
        return self.order_id

    def get_final_amount(self):
        two_places = Decimal(10) ** -2
        tax = Decimal(Decimal("%s" %(tax_rate)) * Decimal(self.total)).quantize(two_places)
        return Decimal(self.total) + Decimal(self.shipping_total) + Decimal(tax)

def pre_save_create_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = unique_order_id_generator(instance)


pre_save.connect(pre_save_create_order_id, sender=Order)

orders/views.py
import time
import stripe
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from accounts.forms import UserAddressForm
from accounts.models import UserAddress
from carts.models import Cart
from .models import Order

try:
    stripe_pub = settings.STRIPE_PUBLISHABLE_KEY
    stripe_secret = settings.STRIPE_SECRET_KEY
except:
    stripe_pub = "pk_test_Lc1VPKGWfVIvUMaBEgdNuNHM00Dsa8akHY"
    stripe_secret = "sk_test_plkTsRU0LvReg1DmHlcR6hZJ00WUC7dZhb"

stripe.api_key = stripe_secret

def orders(request):
    context = {}
    template = "orders/user.html"
    return render(request, template, context)

@login_required
def checkout(request):
    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id = None
        return HttpResponseRedirect(reverse("cart_app:cart", kwargs={}))
    
    try:
        new_order = Order.objects.get(cart=cart)
    except Order.DoesNotExist:
        new_order = Order(cart=cart)
        new_order.cart = cart
        new_order.user = request.user
        new_order.save()
    except:
        new_order = None
        return HttpResponseRedirect(reverse("cart_app:cart", kwargs={}))
    final_amount = 0
    if new_order is not None:
        new_order.total = cart.total
        new_order.save()
        final_amount = new_order.get_final_amount()
    try:
        address_added =request.GET.get("address_added")
    except:
        address_added = None
    if address_added is None:
        address_form = UserAddressForm()
    else:
        address_form = None
    current_address = UserAddress.objects.filter(user=request.user)
    billing_address = UserAddress.objects.get_billing_address(user=request.user)

    if request.method == "POST":
        try:
            user_stripe = request.user.userstripe.stripe_id
            customer = stripe.Customer.retrieve(user_stripe)
        except:
            customer = None
            pass
        if customer is not None:
            try:
                billing_a = request.POST['billing_address']
                shipping_a = request.POST['shipping_address']
            except:
                return HttpResponseRedirect(reverse("orders:checkout", kwargs={}))
            try:
                billing_address_instance = UserAddress.objects.get(id=billing_a)
            except:
                billing_address_instance = None
            try:
                shipping_address_instance = UserAddress.objects.get(id=shipping_a)
            except:
                shipping_address_instance = None
            token = request.POST['stripeToken']
            # card = stripe.Customer.create_source(
            #         user_stripe,
            #         source=token,
            #         )
            charge = stripe.Charge.create(
                amount=int(final_amount * 100),
                currency="inr",
                source=token,
                description="Charge for %s" %(request.user.username),
                )
            # print(charge)
            if charge["captured"]:
                new_order.status = "paid"
                new_order.shipping_address = shipping_address_instance or None
                new_order.billing_address = billing_address_instance or None
                new_order.save()
                del request.session['cart_id']
                messages.success(request, "Thank you for your order!")
                return HttpResponseRedirect(reverse("orders:user-orders", kwargs={}))
        
    context = {
        "order": new_order,
        "final_amount": final_amount,
        "current_address": current_address,
        "address_form": address_form,
        "billing_address": billing_address,
        "stripe_pub": stripe_pub,
        }
    template = "orders/checkout.html"
    return render(request, template, context)

orders/templates/orders/checkout.html
{% extends "base.html" %}
{% block content %}
<!-- input this js in head tag somehow -->
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<!-- input this js in main html tag somehow -->
<script type="text/javascript">
    Stripe.setPublishableKey('{{ stripe_pub }}');
    jQuery(function($){
        $('#payment-form').submit(function(event) {
            var $form = $(this);
            $form.find('button').prop('disabled', true);
            Stripe.card.createToken($form, stripeResponseHandler);
            return false;
        });
    });
    function stripeResponseHandler(status, response) {
        var $form = $('#payment-form');
        if (response.error) {
            $form.find('.payment-errors').text(response.error.message);
            $form.find('button').prop('disabled', false);
        } else {
            var token = response.id;
            $form.append($('<input type="hidden" name="stripeToken" />').val(token));
            $form.get(0).submit();
        }
    };

    $("#addShippingAddress").click(function(){
        $("#shippingAddressForm").fadeToggle()
    })
</script>


<div class="col-sm-3">
    <div class="total">
        <h1>Current total: {{ final_amount }} </h1>
    </div>
</div>
{% if address_form %}
<div class="col-sm-6 float-right" id="shippingAddressForm" style="">
    <h3>Add new Shipping Address</h3>
    <form action="{% url 'orders:add_user_address' %}?next=orders:checkout" method="POST">{% csrf_token %}
        {{ address_form.as_p}}
        <input type="submit" class="btn btn-default" value="Add Address"/>
    </form>
</div>
{% endif %}
<form action="" method="POST" id="payment-form">{% csrf_token %}
    {% if current_address %}
        <div class="col-sm-6">
            <h3>Shipping Addresses</h3>
            {% for address in current_address %}
                <input type="radio" name='shipping_address' value="{{ address.id }}" {% if request.user.userdefaultaddress.shipping.id == address.id %} checked="checked" {% endif %}/>
                {{ address.get_address }} <br/>
            {% endfor %}
            <a href="#" id="addShippingAddress">Add New Address</a>
        </div> 
    {% endif %}
    {% if billing_address %}
        <div class="col-sm-6">
            <h3>Billing Addresses</h3>
            {% for address in billing_address %}
                <input type="radio" name='billing_address' value="{{ address.id }}" {% if request.user.userdefaultaddress.billing.id == address.id %} checked="checked" {% endif %}/> 
                {{ address.get_address }} <br/>
            {% endfor %}
        </div> 
    {% endif %}
    <div class="col-sm-6">
        <h3>Credit card Info</h3>
        <span class="payment-errors"></span>

        <div class="form-row">
            <label>
                <span>Card Number</span>
                <input type="text" size="20" data-stripe="number"/>
            </label>
        </div>

        <div class="form-row">
            <label>
                <span>CVC</span>
                <input type="text" size="4" data-stripe="cvc"/>
            </label>
        </div>

        <div class="form-row">
            <label>
                <span>Expiration (MM/YYYY)</span>
                <input type="text" size="2" data-stripe="exp-month"/>
                <span> / </span>
                <input type="text" size="4" data-stripe="exp-year"/>
            </label>
        </div>
        <button type="submit">Submit Payment</button>
    </div>

</form>
{% endblock content %}

orders/templates/orders/form.html
{% extends "base.html" %}

{% block content %}
<h1>Address Form</h1>
<div class="col-sm-6 col-sm-offset-3" style="margin-top: 50px;">
    <form action="" method="POST">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}" class="btn btn-default" />
    </form>
</div>
{% endblock %}

orders/templates/orders/user.html
{% extends "base.html" %}

{% block content %}

{{ user.order_set.all }}

{% endblock content %}